var mongoose = require('mongoose');

const parametrosAlgoritmoSchema = new mongoose.Schema({
	setup_name:[],
	symbol_name:[],
	symbol_hedge_name_2:[],
	magic_number:[],
	max_op_lot_size_1:[],
	max_op_lot_size_2:[],
	number_1_id:[],
	number_2_id:[],
	a1_lot_size_1:[],
	a1_lot_size_2:[],
	a2_mode_1:[],
	a2_mode_2:[],
	b1_measure_1:[],
	b1_measure_2:[],
	b2_distance_1:[],
	b2_distance_2:[],
	c1_direction_1:[],
	c1_direction_2:[],
	c2_measure_1:[],
	c2_measure_2:[],
	c3_distance_1:[],
	c3_distance_2:[],
	c4_size_1:[],
	c4_size_2:[],
	d1_measure_1:[],
	d1_measure_2:[],
	d2_distance_1:[],
	d2_distance_2:[],
	t1_time_1:[],
	a1_action_1:[],
	f1_filter_1:[],
	t2_time_1:[],
	a2_action_1:[],
	f2_filter_1:[],
	t3_time_1:[],
	a3_action_1:[],
	f3_filter_1:[],
	t4_time_1:[],
	a4_action_1:[],
	f4_filter_1:[],
	t5_time_1:[],
	a5_action_1:[],
	f5_filter_1:[],
	t5_time_1:[],
	a5_action_1:[],
	f5_filter_1:[]

});

module.exports = mongoose.model('parametros_algoritmo', parametrosAlgoritmoSchema,'parametros_algoritmo');